// j/products-data.js

// Цей масив містить повну інформацію про всі товари.
// Він буде імпортуватися в інші скрипти.
// УВАГА: Для використання в звичайних HTML-файлах (не React-додатках),
// тут НЕ ПОВИННО бути "export { allProducts };"
const allProducts = [
    // Товари з index.html
    { id: 1, category: 'beads', name: 'Бісер рожевий 10г', price: 25, image: 'https://placehold.co/200x200/FFC0CB/000000?text=Бісер+Рожевий', color: 'pink', material: 'glass', manufacturer: 'unknown', description: 'Високоякісний рожевий бісер для рукоділля, ідеально підходить для створення прикрас та вишивки.' },
    { id: 2, category: 'threads', name: 'Нитки бавовняні', price: 35, image: 'https://placehold.co/200x200/F5F5DC/000000?text=Нитки+Бавовна', color: 'beige', material: 'cotton', manufacturer: 'unknown', description: 'Натуральні бавовняні нитки, міцні та довговічні, для шиття та рукоділля.' },
    { id: 3, category: 'kits', name: 'Набір для вишивки', price: 150, image: 'https://placehold.co/200x200/D0D0D0/000000?text=Набір+Вишивка', color: 'multi', material: 'mixed', manufacturer: 'unknown', description: 'Повний набір для вишивки хрестиком, включає всі необхідні матеріали та інструкції.' },

    // Бісер та Бісероплетіння
    { id: 101, category: 'beads', name: 'Чеський бісер Preciosa №10 (блакитний)', price: 50, image: 'https://placehold.co/200x200/ADD8E6/000000?text=Бісер+Блакитний', color: 'blue', material: 'glass', manufacturer: 'preciosa', description: 'Високоякісний чеський бісер Preciosa, ідеальний для вишивки та створення прикрас.' },
    { id: 102, category: 'beads', name: 'Чеський бісер Preciosa №10 (червоний)', price: 50, image: 'https://placehold.co/200x200/FF0000/FFFFFF?text=Бісер+Червоний', color: 'red', material: 'glass', manufacturer: 'preciosa', description: 'Яскравий червоний чеський бісер для ваших найсміливіших ідей.' },
    { id: 103, category: 'beads', name: 'Чеський бісер Preciosa №10 (зелений)', price: 50, image: 'https://placehold.co/200x200/008000/FFFFFF?text=Бісер+Зелений', color: 'green', material: 'glass', manufacturer: 'preciosa', description: 'Насичений зелений бісер Preciosa для природних мотивів.' },
    { id: 104, category: 'beads', name: 'Чеський бісер Preciosa №10 (жовтий)', price: 50, image: 'https://placehold.co/200x200/FFFF00/000000?text=Бісер+Жовтий', color: 'yellow', material: 'glass', manufacturer: 'preciosa', description: 'Сонячний жовтий бісер, що додасть яскравості вашим виробам.' },
    { id: 105, category: 'beads', name: 'Набір скляного бісеру (Асорті кольорів)', price: 250, image: 'https://placehold.co/200x200/D0D0D0/000000?text=Бісер+Асорті', color: 'multi', material: 'glass', manufacturer: 'gamma', description: 'Великий набір бісеру різних кольорів для будь-яких проектів.' },
    { id: 106, category: 'beads', name: 'Матовий бісер №8 (чорний)', price: 45, image: 'https://placehold.co/200x200/333333/FFFFFF?text=Бісер+Чорний', color: 'black', material: 'glass', manufacturer: 'artcraft', description: 'Елегантний матовий бісер чорного кольору.' },
    { id: 107, category: 'beads', name: 'Матовий бісер №8 (білий)', price: 45, image: 'https://placehold.co/200x200/FFFFFF/000000?text=Бісер+Білий', color: 'white', material: 'glass', manufacturer: 'artcraft', description: 'Чистий білий матовий бісер для ніжних робіт.' },

    // Нитки та Пряжа
    { id: 201, category: 'threads', name: 'Муліне бавовняне DMC (червоне)', price: 30, image: 'https://placehold.co/200x200/E74C3C/FFFFFF?text=Муліне+Червоне', color: 'red', material: 'cotton', manufacturer: 'dmc', description: 'Високоякісне муліне DMC, стійке до вицвітання.' },
    { id: 202, category: 'threads', name: 'Муліне бавовняне DMC (синє)', price: 30, image: 'https://placehold.co/200x200/3498DB/FFFFFF?text=Муліне+Синє', color: 'blue', material: 'cotton', manufacturer: 'dmc', description: 'Насичений синій відтінок муліне DMC для ваших вишивок.' },
    { id: 203, category: 'threads', name: 'Муліне бавовняне DMC (зелене)', price: 30, image: 'https://placehold.co/200x200/2ECC71/FFFFFF?text=Муліне+Зелене', color: 'green', material: 'cotton', manufacturer: 'dmc', description: 'Зелене муліне DMC, ідеальне для пейзажів та листя.' },
    { id: 204, category: 'threads', name: 'Муліне бавовняне DMC (жовте)', price: 30, image: 'https://placehold.co/200x200/F1C40F/000000?text=Муліне+Жовте', color: 'yellow', material: 'cotton', manufacturer: 'dmc', description: 'Яскраве жовте муліне DMC для сонячних акцентів.' },
    { id: 205, category: 'threads', name: 'Пряжа акрилова 100г (біла)', price: 90, image: 'https://placehold.co/200x200/FFFFFF/000000?text=Пряжа+Біла', color: 'white', material: 'acrylic', manufacturer: 'alize', description: 'М’яка акрилова пряжа, ідеальна для в’язання дитячих речей.' },
    { id: 206, category: 'threads', name: 'Пряжа акрилова 100г (чорна)', price: 90, image: 'https://placehold.co/200x200/333333/FFFFFF?text=Пряжа+Чорна', color: 'black', material: 'acrylic', manufacturer: 'alize', description: 'Класична чорна акрилова пряжа для будь-яких проектів.' },
    { id: 207, category: 'threads', name: 'Вовняна нитка для в’язання 50г (сіра)', price: 75, image: 'https://placehold.co/200x200/95A5A6/000000?text=Нитка+Сіра', color: 'gray', material: 'wool', manufacturer: 'lana-gatto', description: 'Тепла вовняна нитка для створення затишних виробів.' },
    { id: 208, category: 'threads', name: 'Вовняна нитка для в’язання 50г (бежева)', price: 75, image: 'https://placehold.co/200x200/F5F5DC/000000?text=Нитка+Бежева', color: 'beige', material: 'wool', manufacturer: 'lana-gatto', description: 'Ніжна бежева вовняна нитка, універсальна для будь-якого гардеробу.' },
    { id: 209, category: 'threads', name: 'Набір ниток для шиття (12 кольорів)', price: 110, image: 'https://placehold.co/200x200/D0D0D0/000000?text=Набір+Ниток', color: 'multi', material: 'polyester', manufacturer: 'pony', description: 'Базовий набір ниток для шиття, 12 найпопулярніших кольорів.' },

    // Тканини та Основи
    { id: 301, category: 'fabrics', name: 'Бавовняна тканина 1м (синя)', price: 180, image: 'https://placehold.co/200x200/3498DB/FFFFFF?text=Тканина+Синя', color: 'blue', material: 'cotton', manufacturer: 'textile-pro', description: 'Високоякісна бавовняна тканина синього кольору, 1 метр.' },
    { id: 302, category: 'fabrics', name: 'Бавовняна тканина 1м (червона)', price: 180, image: 'https://placehold.co/200x200/E74C3C/FFFFFF?text=Тканина+Червона', color: 'red', material: 'cotton', manufacturer: 'textile-pro', description: 'Яскрава бавовняна тканина червоного кольору, 1 метр.' },
    { id: 303, category: 'fabrics', name: 'Фетр листовий А4 (червоний)', price: 40, image: 'https://placehold.co/200x200/E74C3C/FFFFFF?text=Фетр+Червоний', color: 'red', material: 'felt', manufacturer: 'iskys', description: 'М’який фетр формату А4, ідеальний для аплікацій та декору.' },
    { id: 304, category: 'fabrics', name: 'Фетр листовий А4 (зелений)', price: 40, image: 'https://placehold.co/200x200/2ECC71/FFFFFF?text=Фетр+Зелений', color: 'green', material: 'felt', manufacturer: 'iskys', description: 'Зелений фетр формату А4 для творчих проектів.' },
    { id: 305, category: 'fabrics', name: 'Фетр листовий А4 (жовтий)', price: 40, image: 'https://placehold.co/200x200/F1C40F/000000?text=Фетр+Жовтий', color: 'yellow', material: 'felt', manufacturer: 'iskys', description: 'Сонячний жовтий фетр для яскравих виробів.' },
    { id: 306, category: 'fabrics', name: 'Канва для вишивки Aida 14 (біла)', price: 95, image: 'https://placehold.co/200x200/FFFFFF/000000?text=Канва+Біла', color: 'white', material: 'cotton', manufacturer: 'zweigart', description: 'Класична канва Aida 14 для вишивки хрестиком.' },
    { id: 307, category: 'fabrics', name: 'Канва для вишивки Aida 14 (кремова)', price: 95, image: 'https://placehold.co/200x200/FFFDD0/000000?text=Канва+Кремова', color: 'cream', material: 'cotton', manufacturer: 'zweigart', description: 'Кремова канва Aida 14 для вишивки, надає виробу вінтажного вигляду.' },
    { id: 308, category: 'fabrics', name: 'Плащова тканина 1м (чорна)', price: 220, image: 'https://placehold.co/200x200/333333/FFFFFF?text=Тканина+Чорна', color: 'black', material: 'polyester', manufacturer: 'rainproof-textiles', description: 'Водонепроникна плащова тканина чорного кольору, 1 метр.' },

    // Фурнітура та Декор
    { id: 401, category: 'decor', name: 'Блискавка потайна 20см (чорна)', price: 15, image: 'https://placehold.co/200x200/333333/FFFFFF?text=Блискавка+Чорна', color: 'black', material: 'nylon', manufacturer: 'ykk', description: 'Потайна блискавка чорного кольору, 20 см.' },
    { id: 402, category: 'decor', name: 'Блискавка потайна 20см (біла)', price: 15, image: 'https://placehold.co/200x200/FFFFFF/000000?text=Блискавка+Біла', color: 'white', material: 'nylon', manufacturer: 'ykk', description: 'Потайна блискавка білого кольору, 20 см.' },
    { id: 403, category: 'decor', name: 'Набір дерев\'яних ґудзиків (натуральні)', price: 60, image: 'https://placehold.co/200x200/A0522D/FFFFFF?text=Ґудзики+Дерево', color: 'brown', material: 'wood', manufacturer: 'natural-crafts', description: 'Набір натуральних дерев\'яних ґудзиків для одягу та декору.' },
    { id: 404, category: 'decor', name: 'Набір пластикових ґудзиків (кольоровий мікс)', price: 55, image: 'https://placehold.co/200x200/D0D0D0/000000?text=Ґудзики+Мікс', color: 'multi', material: 'plastic', manufacturer: 'button-co', description: 'Різнокольорові пластикові ґудзики для дитячого одягу та іграшок.' },
    { id: 405, category: 'decor', name: 'Атласна стрічка 25мм х 5м (рожева)', price: 45, image: 'https://placehold.co/200x200/FFC0CB/000000?text=Стрічка+Рожева', color: 'pink', material: 'satin', manufacturer: 'ribbon-art', description: 'Ніжна рожева атласна стрічка для декору та подарунків.' },
    { id: 406, category: 'decor', name: 'Атласна стрічка 25мм х 5м (синя)', price: 45, image: 'https://placehold.co/200x200/3498DB/FFFFFF?text=Стрічка+Синя', color: 'blue', material: 'satin', manufacturer: 'ribbon-art', description: 'Синя атласна стрічка для морських та класичних мотивів.' },
    { id: 407, category: 'decor', name: 'Набір нашивок "Квіти" (для ремонту)', price: 85, image: 'https://placehold.co/200x200/D0D0D0/000000?text=Нашивки+Квіти', color: 'multi', material: 'fabric', manufacturer: 'diy-patches', description: 'Декоративні нашивки у формі квітів для оновлення одягу.' },
    { id: 408, category: 'decor', name: 'Декоративні перлинні намистини (білі)', price: 70, image: 'https://placehold.co/200x200/FFFFFF/000000?text=Намистини+Білі', color: 'white', material: 'plastic', manufacturer: 'glam-decor', description: 'Елегантні перлинні намистини для створення прикрас.' },

    // Набори для Рукоділля
    { id: 501, category: 'kits', name: 'Набір для вишивки бісером "Вечірній пейзаж"', price: 420, image: 'https://placehold.co/200x200/D0D0D0/000000?text=Набір+Бісер', color: 'multi', material: 'mixed', manufacturer: 'abris-art', description: 'Повний набір для створення картини бісером.' },
    { id: 502, category: 'kits', name: 'Набір для вишивки хрестиком "Польові квіти"', price: 350, image: 'https://placehold.co/200x200/D0D0D0/000000?text=Набір+Хрестик', color: 'multi', material: 'mixed', manufacturer: 'zolote-runo', description: 'Набір для вишивки хрестиком, ідеальний для початківців.' },
    { id: 503, category: 'kits', name: 'Набір для в\'язання іграшки "Милий ведмедик"', price: 290, image: 'https://placehold.co/200x200/A0522D/FFFFFF?text=Набір+Ведмедик', color: 'brown', material: 'yarn', manufacturer: 'amigurumi-kits', description: 'Все необхідне для створення милого в’язаного ведмедика.' },
    { id: 504, category: 'kits', name: 'Набір для створення прикрас "Браслети дружби"', price: 190, image: 'https://placehold.co/200x200/D0D0D0/000000?text=Набір+Браслети', color: 'multi', material: 'mixed', manufacturer: 'jewelry-crafts', description: 'Творчий набір для створення унікальних браслетів.' },
    { id: 505, category: 'kits', name: 'Набір для вишивки стрічками "Троянди"', price: 280, image: 'https://placehold.co/200x200/FFC0CB/000000?text=Набір+Стрічки', color: 'pink', material: 'mixed', manufacturer: 'ribbon-dreams', description: 'Елегантний набір для створення об\'ємних вишивок стрічками.' },

    // Інструменти та Допоміжні Матеріали
    { id: 601, category: 'tools', name: 'Набір швейних голок (універсальний)', price: 55, image: 'https://placehold.co/200x200/C0C0C0/000000?text=Набір+Голки', color: 'silver', material: 'metal', manufacturer: 'schmetz', description: 'Універсальний набір швейних голок для різних типів тканин.' },
    { id: 602, category: 'tools', name: 'Ножиці кравецькі 20см (сталеві)', price: 130, image: 'https://placehold.co/200x200/333333/FFFFFF?text=Ножиці', color: 'black', material: 'metal', manufacturer: 'fiskars', description: 'Гострі кравецькі ножиці для точного розкрою тканини.' },
    { id: 603, category: 'tools', name: 'П\'яльця дерев\'яні 20см', price: 70, image: 'https://placehold.co/200x200/A0522D/FFFFFF?text=П\'яльця', color: 'wood', material: 'wood', manufacturer: 'hoop-art', description: 'Класичні дерев\'яні п\'яльця для вишивки.' },
    { id: 604, category: 'tools', name: 'Набір гачків для в\'язання (5шт)', price: 180, image: 'https://placehold.co/200x200/C0C0C0/000000?text=Гачки', color: 'silver', material: 'metal', manufacturer: 'pony', description: 'Набір гачків різних розмірів для в\'язання.' },
    { id: 605, category: 'tools', name: 'Органайзер для бісеру (пластиковий)', price: 90, image: 'https://placehold.co/200x200/E0E0E0/000000?text=Органайзер', color: 'transparent', material: 'plastic', manufacturer: 'box-it', description: 'Зручний органайзер для зберігання бісеру та дрібних деталей.' },
    { id: 606, category: 'tools', name: 'Набір маркерів для тканини (4 кол.)', price: 100, image: 'https://placehold.co/200x200/D0D0D0/000000?text=Маркери+Тканина', color: 'multi', material: 'plastic', manufacturer: 'fabric-marker-pro', description: 'Маркери, що зникають, для розмітки на тканині.' },
];
